#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @copyright Copyright (c) 2011 Stephane Bocquet
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


GREYHOLE_CONFIG="/etc/greyhole.conf"
GREYHOLE_INIT="greyhole"

# Enable/disable service
if [ "$(omv_config_get "//services/greyhole/enable")" != "1" ]; then
	/etc/init.d/${GREYHOLE_INIT} stop
	update-rc.d ${GREYHOLE_INIT} disable
	exit 0
fi

# xmlstarlet sel -t -m "//services/greyhole" \
#  -v "concat('option domain-name &quot;', domain-name, '&quot;;')" -n \
#  -i "string-length(name-servers) > 0" \
#  	-v "concat('option domain-name-servers ', name-servers, ';')" -n -b \
#  -v "concat('option routers ', gateway, ';')" -n \
#  -i "string-length(bootfile) > 0" \
#     -v "concat('    filename &quot;', bootfile, '&quot;;')" -n -b \
# ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${GREYHOLE_CONFIG}


xmlstarlet sel -t -m "//services/greyhole" \
	-v "concat('email_to = ',email_to)" -n \
	-v "concat('log_level = ',log_level)" -n \
	-v "concat('delete_moves_to_trash = ',delete_moves_to_trash)" -n \
	-v "concat('balance_modified_files = ',balance_modified_files)" -n \
	-v "concat('db_engine = ',db_engine)" -n \
	-v "concat('db_host = ',db_host)" -n \
	-v "concat('db_user = ',db_user)" -n \
	-v "concat('db_pass = ',db_pass)" -n \
	-v "concat('db_name = ',db_name)" -n \
	${OMV_CONFIG_FILE} | xmlstarlet unesc > ${GREYHOLE_CONFIG}

/etc/init.d/${GREYHOLE_INIT} restart
update-rc.d ${GREYHOLE_INIT} enable
update-rc.d ${GREYHOLE_INIT} defaults
