#!/bin/sh

# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Stephane Bocquet <stephane_bocquet@hotmail.com>
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2011 Stephane Bocquet
# @copyright Copyright (c) 2011-2012 Marcel Beck
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Only if enabled
if [ "$(omv_config_get "//system/storage/greyhole/enable")" != "1" ]; then
	exit 0
fi

GREYHOLE_CONFIG="/etc/greyhole.conf"

echo "#======================= Greyhole Shares =======================" >> ${GREYHOLE_CONFIG}

index=$(omv_config_get_count "//system/storage/greyhole/smb_shares/share")
while [ ${index} -gt 0 ]
do
	xmlstarlet sel -t -m "//system/storage/greyhole/smb_shares/share[position()=${index}]" \
	  -v "concat('num_copies[',num_copies,']')" -n \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${GREYHOLE_CONFIG}

	index=$(( ${index} - 1 ))
done